import React, { useEffect, useState } from "react";

function Analytics() {
  const [analytics, setAnalytics] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const fetchAnalytics = async () => {
      try {
        setLoading(true);

        const response = await fetch(
          "http://127.0.0.1:8000/api/analytics"
        );

        if (!response.ok) {
          throw new Error("Failed to load analytics");
        }

        const data = await response.json();

        setAnalytics(data);
        setError("");
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    fetchAnalytics();
  }, []);

  if (loading) {
    return (
      <div className="page">
         <div className="analytics-loading">
          Loading analytics...
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="page">
        

        <div className="analytics-error">
          <strong>Unable to load analytics</strong>
          <span>{error}</span>

          <button onClick={() => window.location.reload()}>
            Retry
          </button>
        </div>
      </div>
    );
  }

  const priorityDistribution =
    analytics?.priority_distribution || {};

  return (
    <div className="page">

      {/* HEADER */}

      

      {/* KPI CARDS */}

      <div className="analytics-grid">

        <div className="analytics-card">
          <span className="analytics-label">
            Optimization Runs
          </span>

          <strong>
            {analytics.total_runs}
          </strong>

          <small>
            Completed optimization runs
          </small>
        </div>

        <div className="analytics-card">
          <span className="analytics-label">
            Average Score
          </span>

          <strong>
            {analytics.average_score.toFixed(1)}
          </strong>

          <small>
            Schedule quality score
          </small>
        </div>

        <div className="analytics-card">
          <span className="analytics-label">
            Tasks Scheduled
          </span>

          <strong>
            {analytics.total_tasks_scheduled}
          </strong>

          <small>
            Maintenance tasks optimized
          </small>
        </div>

        <div className="analytics-card">
          <span className="analytics-label">
            Assets Scheduled
          </span>

          <strong>
            {analytics.assets_scheduled}
          </strong>

          <small>
            Assets included in schedules
          </small>
        </div>

      </div>

      {/* MAIN ANALYTICS */}

      <div className="analytics-panels">

        {/* PRIORITY */}

        <section className="analytics-panel">
          <div className="panel-header">
            <div>
              <h3>Priority Distribution</h3>
              <p>
                Scheduled maintenance by priority
              </p>
            </div>
          </div>

          <div className="priority-list">

            <div className="priority-row">
              <span>Critical</span>
              <strong>
                {priorityDistribution.critical || 0}
              </strong>
            </div>

            <div className="priority-row">
              <span>High</span>
              <strong>
                {priorityDistribution.high || 0}
              </strong>
            </div>

            <div className="priority-row">
              <span>Medium</span>
              <strong>
                {priorityDistribution.medium || 0}
              </strong>
            </div>

            <div className="priority-row">
              <span>Low</span>
              <strong>
                {priorityDistribution.low || 0}
              </strong>
            </div>

          </div>
        </section>

        {/* RECENT RUNS */}

        <section className="analytics-panel">

          <div className="panel-header">
            <div>
              <h3>Recent Optimization Runs</h3>
              <p>
                Latest schedules generated by RailGenie
              </p>
            </div>
          </div>

          <div className="runs-table">

            {analytics.recent_runs?.length ? (
              analytics.recent_runs.map((run) => (
                <div
                  className="run-row"
                  key={run.run_id}
                >
                  <div>
                    <strong>
                      Run #{run.run_id}
                    </strong>

                    <small>
                      {new Date(
                        run.created_at
                      ).toLocaleString()}
                    </small>
                  </div>

                  <span
                    className={
                      run.status === "optimal"
                        ? "status-success"
                        : "status-neutral"
                    }
                  >
                    {run.status}
                  </span>

                  <strong>
                    {run.score?.toFixed(1)}
                  </strong>
                </div>
              ))
            ) : (
              <div className="empty-state">
                No optimization runs yet.
              </div>
            )}

          </div>

        </section>

      </div>

    </div>
  );
}

export default Analytics;